allowBuilds:
  core-js: false
  es5-ext: false
minimumReleaseAgeExclude:
  - '@tiptap/core@3.30.3'
  - '@tiptap/extension-blockquote@3.30.3'
  - '@tiptap/extension-bold@3.30.3'
  - '@tiptap/extension-bubble-menu@3.30.3'
  - '@tiptap/extension-bullet-list@3.30.3'
  - '@tiptap/extension-code-block@3.30.3'
  - '@tiptap/extension-code@3.30.3'
  - '@tiptap/extension-document@3.30.3'
  - '@tiptap/extension-dropcursor@3.30.3'
  - '@tiptap/extension-floating-menu@3.30.3'
  - '@tiptap/extension-gapcursor@3.30.3'
  - '@tiptap/extension-hard-break@3.30.3'
  - '@tiptap/extension-heading@3.30.3'
  - '@tiptap/extension-horizontal-rule@3.30.3'
  - '@tiptap/extension-image@3.30.3'
  - '@tiptap/extension-italic@3.30.3'
  - '@tiptap/extension-link@3.30.3'
  - '@tiptap/extension-list-item@3.30.3'
  - '@tiptap/extension-list-keymap@3.30.3'
  - '@tiptap/extension-list@3.30.3'
  - '@tiptap/extension-ordered-list@3.30.3'
  - '@tiptap/extension-paragraph@3.30.3'
  - '@tiptap/extension-strike@3.30.3'
  - '@tiptap/extension-table@3.30.3'
  - '@tiptap/extension-task-item@3.30.3'
  - '@tiptap/extension-task-list@3.30.3'
  - '@tiptap/extension-text@3.30.3'
  - '@tiptap/extension-underline@3.30.3'
  - '@tiptap/extensions@3.30.3'
  - '@tiptap/markdown@3.30.3'
  - '@tiptap/pm@3.30.3'
  - '@tiptap/react@3.30.3'
  - '@tiptap/starter-kit@3.30.3'
